### ISSUE TITLE
Storyboard support

### ISSUE THREAD

**Issue by kevinrenskers** [slackhq/SlackTextViewController#16]
I'd like to be able to assign the tableview as an IBOutlet from a storyboard, so I can also use prototype cells for example. 

A bigger problem however is that I'm not calling any of the init methods when the controller is instantiated from the storyboard, so it would be handy to be able to call `tableViewWithStyle:` and `commonInit` from within my `initWithCoder:` method. Or that SlackTextViewController would implement the `initWithCoder:` method?

**Comment by markst** [comment]
Sorry to dig up old bones!

But it seems that it's still no possible to instantiate a `SLKTextViewController` subclass using storyboard. Since the outlets aren't connected before `initWithCoder` initialer, the `tableViewWithStyle:` will create a table view, which later gets replaced by the storyboard table view once the outlet does get connected. This proves to be an issue once the constraints are setup (`slk_setupViewConstraints`) since the `scrollViewProxy` property is initialised with the lazy created table view, rather than the outlet connected table view...
