### ISSUE TITLE
Who can tell me how to resize the tableView? 

### ISSUE THREAD

**Issue by wyn15811017** [slackhq/SlackTextViewController#597]
#### Description
When I added a customer navigationView, the tableViewCell was hidden behind the navigationView. so I want to adjust the top margin of tableView, who can help me?

refer to below image
![img_4165](https://cloud.githubusercontent.com/assets/12561181/25740715/aa3c0596-31c2-11e7-8ee2-730ee31f0001.png)

**Comment by mzgnr** [comment]
Did you try 

> tableView?.contentInset

**Comment by wyn15811017** [comment]
Thank you! 
I solved this problem as you said.

**Comment by JacobJT** [comment]
To add on to @mzgnr , `tableView?.contentInset = .zero` and `tableVIew?.clipsToBounds = true`.  Without the latter, I had some weird issues with cells flickering under my navigation bar, even though I had my tableView's top bound to the bottom of a custom view on my UIViewController that was beneath the nav bar. It was some odd behavior.

**Comment by mzgnr** [comment]
@JacobJT i've recently started using this project i think i cant help you about this until i face it and find a solution for it. But I'm guessing that this kind of issues can be fixed in super class of SLKTextViewController. I'm not sure how tho 😢

**Comment by mzgnr** [comment]
@JacobJT on the other hand i might help you if you provide a code snippet that i can test

**Comment by JacobJT** [comment]
@mzgnr  Thanks for the offer! I appreciate it. This issue is resolved for me, though. I thought it was odd, because when I scroll all the way up on my table, the last cell would be where you'd expect it to be with my constraints, but when I scrolled all the way down, I'd see the cells flickering under the nav bar.  That's why I added clipsToBounds, which solved that issue. 

The Nav Bar issue stems from some legacy code that used a transparent image as the bar. I'm getting ready to completely redo those pages anyway, though, so I'm not wholly concerned about it at this time.
